### ISSUE TITLE
Error When Generating

### ISSUE THREAD

**Issue by CollinHerber** [ikemtz/openapi-ts-generator#103]
```log
$ node update-services.ts 
C:\dev\betsy\app\node_modules\openapi-ts-generator\openapidoc-converter.js:266
            isEnum: (propertySchema.enum || []).length > 0,
                                    ^

TypeError: Cannot read properties of undefined (reading 'enum')
    at OpenApiDocConverter.convertReferenceObjectToPropertyType (C:\dev\betsy\app\node_modules\openapi-ts-generator\openapidoc-converter.js:266:37)
    at OpenApiDocConverter.buildSchemaWrapperInfo (C:\dev\betsy\app\node_modules\openapi-ts-generator\openapidoc-converter.js:104:69)
    at OpenApiDocConverter.convertEntities (C:\dev\betsy\app\node_modules\openapi-ts-generator\openapidoc-converter.js:55:26)
    at OpenApiDocConverter.convertDocument (C:\dev\betsy\app\node_modules\openapi-ts-generator\openapidoc-converter.js:27:29)
    at Object.<anonymous> (C:\dev\betsy\app\node_modules\openapi-ts-generator\index.js:59:46)
    at step (C:\dev\betsy\app\node_modules\openapi-ts-generator\index.js:33:23)
    at Object.next (C:\dev\betsy\app\node_modules\openapi-ts-generator\index.js:14:53)
    at fulfilled (C:\dev\betsy\app\node_modules\openapi-ts-generator\index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0

```

Can find a copy of my openapi spec here: https://qa.betsybot.xyz/betsyapi-qa/swagger/v1/swagger.json
It is   "openapi": "3.0.1", generated from a .NET project. Works in other systems.

**Comment by ikemtz** [comment]
@CollinHerber Thanks for providing me with your swagger.json doc.  This should be functional now with the latest version.
