### ISSUE TITLE
Add support for local OpenAPI spec

### ISSUE THREAD

**Issue by arikon** [ikemtz/openapi-ts-generator#3]
For now it is throwing a error:

```
(node:63009) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/node-fetch/lib/index.js:1299:9)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at Function.fetch [as default] (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/node-fetch/lib/index.js:1401:9)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:72:66
    at step (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:33:23)
    at Object.next (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:14:53)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:4:12)
(node:63009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:63009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The code is:
```js
const generator = require('openapi-ts-generator');

generator.generateTsModels({
    openApiJsonUrl: '../har2openapi/output/generated.json',
    outputPath: './src/',
});
```

**Comment by ikemtz** [comment]
This issue has been fixed, just give it a few minutes for the changes to flow through the CiCd pipeline.

The readme.md has been updated, but the code you referenced above should be changed to:
````javascript
const generator = require('openapi-ts-generator');

generator.generateTsModels({
    openApiJsonFileName: '../har2openapi/output/generated.json',
    outputPath: './src/',
});
````

**Comment by arikon** [comment]
Thanks!

**Comment by arikon** [comment]
It is not working nor with relative paths, nor with absolute:

```
(node:23109) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/../har2openapi/output/generated.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:83:39
    at step (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:33:23)
    at Object.next (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:14:53)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:4:12)
    at getOpenApiDocumentAsync (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:68:12)
    at Object.<anonymous> (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:55:42)
(node:23109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23109) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
(node:23124) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib//Users/arikon/projects/smart-oil/har2openapi/output/generated.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:83:39
    at step (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:33:23)
    at Object.next (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:14:53)
    at /Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:4:12)
    at getOpenApiDocumentAsync (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:68:12)
    at Object.<anonymous> (/Users/arikon/projects/smart-oil/openapi-ts-generator-test/node_modules/openapi-ts-generator/lib/index.js:55:42)
(node:23124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
